/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.php',
    './inc/**/*.php',
    './template-parts/**/*.php',
    './woocommerce/**/*.php',
    './assets/js/**/*.js',
  ],
  // WooCommerce, WordPress core and select2 print these class names at runtime,
  // so the content scanner never sees them in the theme source. Without the
  // safelist their rules are tree-shaken out of the build.
  // Regenerate with: npm run audit:safelist
  safelist: [
    'aligncenter',
    'alignfull',
    'alignleft',
    'alignright',
    'alignwide',
    'blockOverlay',
    'blockUI',
    'bypostauthor',
    'columns-2',
    'columns-3',
    'columns-4',
    'columns-5',
    'comment-body',
    'current-cat',
    'disabled',
    'flex-active',
    'flex-control-nav',
    'flex-control-thumbs',
    'flex-viewport',
    'gallery-caption',
    'is-active',
    'loader',
    'nav-links',
    'no-comments',
    'notes',
    'page-numbers',
    'payment_box',
    'payment_methods',
    'select2-container',
    'select2-container--default',
    'select2-selection--single',
    'select2-selection__arrow',
    'single_add_to_cart_button',
    'star-rating',
    'wc-block-components-button',
    'woocommerce-Tabs-panel',
    'woocommerce-additional-fields',
    'woocommerce-address-fields__field-wrapper',
    'woocommerce-billing-fields__field-wrapper',
    'woocommerce-error',
    'woocommerce-info',
    'woocommerce-input-wrapper',
    'woocommerce-message',
    'woocommerce-noreviews',
    'woocommerce-ordering',
    'woocommerce-pagination',
    'woocommerce-product-gallery',
    'woocommerce-product-gallery__image',
    'woocommerce-product-gallery__trigger',
    'woocommerce-product-gallery__wrapper',
    'woocommerce-product-rating',
    'woocommerce-result-count',
    'woocommerce-review-link',
    'woocommerce-shipping-fields',
    'woocommerce-shipping-fields__field-wrapper',
    'woocommerce-tabs',
    'wp-caption',
    'wp-caption-text',
    { pattern: /^(grid-cols|col-span)-(1|2|3|4|5|6|12)$/, variants: ['sm', 'md', 'lg', 'xl'] },
  ],
  theme: {
    extend: {
      colors: {
        green: {
          DEFAULT: '#00a63e',
          dark: '#058a36',
          soft: '#e8f8ee',
        },
        ink: '#1b1b1b',
        muted: '#6b7280',
        surface: '#f3f5f7',
        line: '#e6e9ec',
      },
      fontFamily: {
        bangla: ['"Hind Siliguri"', 'sans-serif'],
        display: ['"Poppins"', '"Hind Siliguri"', 'sans-serif'],
      },
      maxWidth: {
        container: '1200px',
      },
      boxShadow: {
        card: '0 6px 24px rgba(16, 24, 40, 0.08)',
      },
    },
  },
  corePlugins: {
    // WordPress core + WooCommerce ship their own float/clear helpers.
    container: false,
  },
  plugins: [],
};
